using System.Text.RegularExpressions;
public partial class BMSReader{
// #if CSHARP_11_OR_LATER || NET7_0_OR_GREATER
// #else
// #endif
    private const RegexOptions options = StaticClass.regexOption;
    private const string notLetter = @"([^a-zA-Z_]|$)";
    private const string floatLower = @"(\.\d+)?([Ee][\+\-]*\d+)?";
    // private const string hexRegStr = @"0[Xx][\da-fA-F]+";
    // private const string unumRegStr = @"\d+";
    private const string numRegStr = @"[\+\-]*\d";
    private const string base36 = @"[\da-zA-Z]{2}";
    private const string base16 = @"[\da-fA-F]{2}";
    private static readonly Regex bmsExt = new Regex(@"\.[Bb][Mm][SsEeLl]$", options);
    // private static readonly Regex pmsExt = new Regex(@"\.[Pp][Mm][Ss]$", options);
    private static readonly Regex videoExt = new Regex(@"^\.(ogv|webm|vp8|mpg|mpeg|mp4|mov|m4v|dv|wmv|avi|asf|3gp|mkv|m2p|flv|swf|ogm)$", options | RegexOptions.IgnoreCase);
    private static readonly Regex picExt = new Regex(@"^\.(bmp|png|jpg|jpeg|gif|mag|wmf|emf|cur|ico|tga|dds|dib|tiff|webp|pbm|pgm|ppm|xcf|pcx|iff|ilbm|pxr|svg|psd)$", options | RegexOptions.IgnoreCase);
    private static readonly Regex intReg = new Regex($@"{numRegStr}+", options);
    private static readonly Regex uintReg = new Regex(@"\d+", options);
    private static readonly Regex floatReg = new Regex($"{numRegStr}+{floatLower}", options);
    private static readonly Regex ifCmd = new Regex($@"^#[Ii][Ff]{notLetter}", options);
    private static readonly Regex endifCmd = new Regex($@"^#[Ee][Nn][Dd]\s*[Ii][Ff]{notLetter}", options);
    private static readonly Regex ranCmd = new Regex($@"^#[Rr][Aa][Nn][Dd][Oo][Mm]{notLetter}", options);
    private static readonly Regex setRanCmd = new Regex($@"^#[Ss][Ee][Tt][Rr][Aa][Nn][Dd][Oo][Mm]{notLetter}", options);
    private static readonly Regex bpmCmd = new Regex($@"^#[Bb][Pp][Mm]\s+{numRegStr}", options);
    private static readonly Regex genreCmd = new Regex($@"^#[Gg][Ee][Nn][RrLl][Ee]{notLetter}", options);
    private static readonly Regex titleCmd = new Regex($@"^#[Tt][Ii][Tt][Ll][Ee]{notLetter}", options);
    private static readonly Regex subtitleCmd = new Regex($@"^#[Ss][Uu][Bb][Tt][Ii][Tt][Ll][Ee]{notLetter}", options);
    private static readonly Regex artistCmd = new Regex($@"^#[Aa][Rr][Tt][Ii][Ss][Tt]{notLetter}", options);
    private static readonly Regex exbpmsCmd = new Regex($@"^#([Ee][Xx])?[Bb][Pp][Mm]{base36}\s+{numRegStr}", options);
    private static readonly Regex pairReg = new Regex($@"{base36}\s+{numRegStr}+{floatLower}", options);
    private static readonly Regex lnobjCmd = new Regex($@"^#[Ll][Nn][Oo][Bb][Jj]\s+{base36}", options);
    private static readonly Regex bmpCmd = new Regex($@"^#[Bb][Mm][Pp]{base36}\s", options);
    private static readonly Regex wavCmd = new Regex($@"^#[Ww][Aa][Vv]{base36}\s", options);
    private static readonly Regex stopCmd = new Regex($@"^#[Ss][Tt][Oo][Pp]{base36}\s+{numRegStr}", options);
    private static readonly Regex stagefileCmd = new Regex(@"^#[Ss][Tt][Aa][Gg][Ee][Ff][Ii][Ll][Ee]\s", options);
    private static readonly Regex totalCmd = new Regex($@"^#[Tt][Oo][Tt][Aa][Ll]\s+{numRegStr}", options);
    private static readonly Regex levelCmd = new Regex($@"^#[Pp][Ll][Aa][Yy][Ll][Ee][Vv][Ee][Ll]\s+{numRegStr}", options);
    private static readonly Regex diffCmd = new Regex($@"^#[Dd][Ii][Ff][Ff][Ii][Cc][Uu][Ll][Tt][Yy]\s+{numRegStr}", options);
    private static readonly Regex backbmpCmd = new Regex(@"^#[Bb][Aa][Cc][Kk][Bb][Mm][Pp]\s", options);
    private static readonly Regex rankCmd = new Regex($@"^#[Rr][Aa][Nn][Kk]\s+{numRegStr}", options);
    private static readonly Regex lnmodeCmd = new Regex(@"^#[Ll][Nn][Mm][Oo][Dd][Ee]\s+\d", options);
    private static readonly Regex scrCmd = new Regex($@"^#[Ss]([Cc][Rr][Oo][Ll][Ll]|[Pp][Ee][Ee][Dd]){base36}\s", options);
    private static readonly Regex scrChCmd = new Regex(@"^#\d{3}[Ss][CcPp]:", options);
    private static readonly Regex meterCmd = new Regex(@"^#\d{3}02:" + numRegStr, options);
    private static readonly Regex channelCmd = new Regex(@"^#\d{3}" + $"{base36}:({base36})+", options);
    private static readonly Regex bpmChCmd = new Regex(@"^#\d{3}03:" + $"({base16})+", options);
    private static readonly Regex exbpmChCmd = new Regex(@"^#\d{3}08:" + $"({base36})+", options);
    private static readonly Regex stopChCmd = new Regex(@"^#\d{3}09:" + $"({base36})+", options);
    private static readonly Regex landmineReg = new Regex(@"^[DdEe][1-9]$", options);
    private static readonly Regex lnReg = new Regex(@"^[56][1-9]$", options);
    private static readonly Regex hidNoteReg = new Regex(@"^[34][1-9]$", options);
    private static readonly Regex bmeNoteReg = new Regex(@"^[12][1-9]$", options);
    private static readonly Regex bmlNotesReg = new Regex(@"^[1256DdEe][1-689]$", options);
    private static readonly Regex bml7kReg = new Regex(@"^[15Dd][89]$", options);
    private static readonly Regex bml10kReg = new Regex(@"^[26Ee][1-6]$", options);
    private static readonly Regex bml14kReg = new Regex(@"^[26Ee][89]$", options);
    private static readonly Regex hid7kReg = new Regex(@"3[89]", options);
    private static readonly Regex hid10kReg = new Regex(@"4[1-6]", options);
    private static readonly Regex hid14kReg = new Regex(@"4[89]", options);
    private static readonly Regex pmsNotesReg = new Regex(@"^[1256DdEe][1-9]$", options);
    private static readonly Regex pmsBmeSReg = new Regex(@"^[15Dd][6-9]$", options);
    private static readonly Regex pmsDReg = new Regex(@"^[26Ee][2-5]$", options);
    private static readonly Regex pmsBmeDReg = new Regex(@"^[26Ee][16-9]$", options);
    private static readonly Regex hidPmsBmeSReg = new Regex(@"3[6-9]", options);
    private static readonly Regex hidPmsDReg = new Regex(@"4[2-5]", options);
    private static readonly Regex hidPmsBmeDReg = new Regex(@"4[16-9]", options);
}